services:
   - type: web
     name: finance-app-backend
     env: node
     rootDir: backend
     buildCommand: npm install && npm run build && npm run knex -- migrate:latest
     startCommand: npm start
